# Generated by Django 5.2.12 on 2026-03-16 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uazapi_message_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('sticker', 'Sticker'), ('location', 'Localização'), ('contact', 'Contato')], default='text', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='sent', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=1000)),
                ('media_mime', models.CharField(blank=True, max_length=80)),
                ('media_filename', models.CharField(blank=True, max_length=255)),
                ('media_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('audio_transcription', models.TextField(blank=True)),
                ('audio_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('quoted_message_id', models.CharField(blank=True, max_length=120)),
                ('quoted_content', models.TextField(blank=True)),
                ('quoted_media_url', models.URLField(blank=True, max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
